development:
  secret_key_base: makesuretochangethisifyoucareaboutdevelopmentenvironmentforsomereason
test:
  secret_key_base: makesuretochangethisifyoucareabouttestenvironmentforsomereason
staging:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
